name: bess
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg_provider: ^1.0.3
  font_awesome_flutter: ^10.1.0
  google_fonts: ^2.3.2
  provider: ^6.0.2
  uuid: 3.0.6
  file_picker: ^5.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/